name: Application CI
on:
  push:
    branches:
      - master

jobs:
    applications:
        name: java-calculator test suite
        runs-on: ubuntu-latest
        timeout-minutes: 40
        steps:
            - uses: actions/setup-java@v1
              name: prepare java
              with:
                java-version: '11.x'
            - uses: actions/checkout@v1
              name: check out
            - name: clean
              run: mvn -ntp clean
            - name: validate
              run: mvn -ntp validate
            - name: compile
              run: mvn -ntp compile -Dmaven.test.skip=true -Djacoco.skip=true -Dcheckstyle.skip=true
            - name: test and code coverage
              run: mvn -ntp test -Dcheckstyle.skip=true -Dpmd.skip=true
            - name: run static analysis
              run: mvn -ntp sonar:sonar
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: check quality goals
              run: |
                sleep 2
                qg_status=$(curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=RicaStach_Java-Calculator" | jq -r .projectStatus.status)
                echo "Quality Gate status is ${qg_status}"

                if [ "${qg_status}" != "OK" ]; then exit 1; fi
            - name: create package
              run: mvn -ntp package -Dclean.skip=true -Dmaven.test.skip=true -Djacoco.skip=true -Dcheckstyle.skip=true
            - name: deploy
              uses: actions/upload-artifact@v1
              with:
                name: java-calculator
                path: target/java-calculator-1.0-SNAPSHOT.jar
